### ISSUE TITLE
allow setting of AD groups as managers

### ISSUE THREAD

**Issue by davidsteinsland** [navikt/kafka-adminrest#16]
instead of creating a new group for every topic, it would be nice to be able to set the manager's group ourselves. That way it's easier to add/remove members.

**Comment by ybelMekk** [comment]
@tronghn , What do you think, should i start analyse this?

**Comment by tronghn** [comment]
This might be a larger task due to the nature of coupling between the automatically created manager groups and topics (e.g. auth[n|z]. membership checks, different environments). If I'm correct in assuming that @davidsteinsland wants to use Azure AD groups for managing these groups then we'll have to implement manager membership checks against production AD as I believe these groups are only synced to that environment. 

We also need to somehow store the mapping for the given manager group ID and topic somewhere for later lookups. As of right now, the manager groups are automatically inferred from the topic name. Perhaps we could add a group/groupId as a 'member' for the automatically created manager group? 

You're free to start analysis if you want to @ybelMekk, just be aware of the above.

**Comment by ybelMekk** [comment]
yes, i agree, me and Torstein talked about it some weeks before new years, and it sound like a v2 of the api.

**Comment by ttnesby** [comment]
After a discussion between Youssef, Trong and me.
@tronghn's summary is a good one, just a couple of questions;

a. Has someone worked out the specifics related to the general topic - team and management of relevant resources (vault, database, kafka topics, ...) related to whatever solutions the team is responsible for? 

b. From (a), is Azure AD group the "official" solution only, or do we need to consider local AD groups (0000_something) as well?  Would be nice to 'minimize; with Azure AD only

In addition, the kafka admin rest should offer an endpoint, transfer existing topics with independent manager group to "team manager group".

**Comment by ttnesby** [comment]
Had a meeting with internal security architect, and due to the current situation, in transit to cloud, we would like to postpone this issue until we know more (kafka in cloud, which cloud, on-prem groups versus cloud groups, ...). But, Youssef will look into "group of groups", thus, the KM group can host whatever manager group a team is using.
